name: Node.js Package

on:
  release:
    types: [created]
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      # Remove prepare script to avoid circular dependency
      - run: npm pkg delete scripts.prepare
      
      # Install dependencies
      - run: npm install
      
      # Install TypeScript globally and locally
      - run: npm install -g typescript
      - run: npm install --save-dev typescript@latest
      
      # Verify TypeScript installation
      - run: npx tsc --version
      
      # Now run the build
      - run: npx tsc
      - run: npm test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
      - run: npm pkg delete scripts.prepare
      - run: npm install
      - run: npx tsc